// Mapping of Symbol Token to Friendly Name
export const NIFTY_50_SYMBOLS = [
  { symbol: "NSE:ADANIENT-EQ", name: "Adani Enterprises" },
  { symbol: "NSE:ADANIPORTS-EQ", name: "Adani Ports" },
  { symbol: "NSE:APOLLOHOSP-EQ", name: "Apollo Hospitals" },
  { symbol: "NSE:ASIANPAINT-EQ", name: "Asian Paints" },
  { symbol: "NSE:AXISBANK-EQ", name: "Axis Bank" },
  { symbol: "NSE:BAJAJ-AUTO-EQ", name: "Bajaj Auto" },
  { symbol: "NSE:BAJFINANCE-EQ", name: "Bajaj Finance" },
  { symbol: "NSE:BAJAJFINSV-EQ", name: "Bajaj Finserv" },
  { symbol: "NSE:BPCL-EQ", name: "BPCL" },
  { symbol: "NSE:BHARTIARTL-EQ", name: "Bharti Airtel" },
  { symbol: "NSE:BRITANNIA-EQ", name: "Britannia" },
  { symbol: "NSE:CIPLA-EQ", name: "Cipla" },
  { symbol: "NSE:COALINDIA-EQ", name: "Coal India" },
  { symbol: "NSE:DIVISLAB-EQ", name: "Divi's Lab" },
  { symbol: "NSE:DRREDDY-EQ", name: "Dr. Reddy's" },
  { symbol: "NSE:EICHERMOT-EQ", name: "Eicher Motors" },
  { symbol: "NSE:GRASIM-EQ", name: "Grasim" },
  { symbol: "NSE:HCLTECH-EQ", name: "HCL Tech" },
  { symbol: "NSE:HDFCBANK-EQ", name: "HDFC Bank" },
  { symbol: "NSE:HDFCLIFE-EQ", name: "HDFC Life" },
  { symbol: "NSE:HEROMOTOCO-EQ", name: "Hero MotoCorp" },
  { symbol: "NSE:HINDALCO-EQ", name: "Hindalco" },
  { symbol: "NSE:HINDUNILVR-EQ", name: "Hindustan Unilever" },
  { symbol: "NSE:ICICIBANK-EQ", name: "ICICI Bank" },
  { symbol: "NSE:ITC-EQ", name: "ITC" },
  { symbol: "NSE:INDUSINDBK-EQ", name: "IndusInd Bank" },
  { symbol: "NSE:INFY-EQ", name: "Infosys" },
  { symbol: "NSE:JSWSTEEL-EQ", name: "JSW Steel" },
  { symbol: "NSE:KOTAKBANK-EQ", name: "Kotak Bank" },
  { symbol: "NSE:LT-EQ", name: "L&T" },
  { symbol: "NSE:LTIM-EQ", name: "LTIMindtree" },
  { symbol: "NSE:M&M-EQ", name: "M&M" },
  { symbol: "NSE:MARUTI-EQ", name: "Maruti Suzuki" },
  { symbol: "NSE:NTPC-EQ", name: "NTPC" },
  { symbol: "NSE:NESTLEIND-EQ", name: "Nestle India" },
  { symbol: "NSE:ONGC-EQ", name: "ONGC" },
  { symbol: "NSE:POWERGRID-EQ", name: "Power Grid" },
  { symbol: "NSE:RELIANCE-EQ", name: "Reliance" },
  { symbol: "NSE:SBILIFE-EQ", name: "SBI Life" },
  { symbol: "NSE:SBIN-EQ", name: "SBI" },
  { symbol: "NSE:SUNPHARMA-EQ", name: "Sun Pharma" },
  { symbol: "NSE:TCS-EQ", name: "TCS" },
  { symbol: "NSE:TATACONSUM-EQ", name: "Tata Consumer" },
  { symbol: "NSE:TATAMOTORS-EQ", name: "Tata Motors" },
  { symbol: "NSE:TATASTEEL-EQ", name: "Tata Steel" },
  { symbol: "NSE:TECHM-EQ", name: "Tech Mahindra" },
  { symbol: "NSE:TITAN-EQ", name: "Titan" },
  { symbol: "NSE:ULTRACEMCO-EQ", name: "UltraTech Cement" },
  { symbol: "NSE:UPL-EQ", name: "UPL" },
  { symbol: "NSE:WIPRO-EQ", name: "Wipro" }
];